server:
  port: 8888

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/dbs1?serverTimezone=UTC&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  shardingsphere:
    datasource:
      names: dbs1
      dbs1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/dbs1?useSSL=false&characterEncoding=utf-8
        username: root
        password: root
        max-active: 16
    sharding:
      tables:
        online_order:
          actual-data-nodes: dbs1.online_order$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: online_order$->{id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
      binding-tables: online_order

